name: release

on:
  release:
    types: [published]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pypi-publish:
    name: Upload release to PyPi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/elt-dagster-meltano/
    permissions:
      # Required for trusted publishing
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Python 3.11
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.11
          architecture: x64
          cache: "pip"
          cache-dependency-path: "poetry.lock"

      - name: Install Poetry
        run: pipx install poetry

      - name: Package project
        run: poetry build

      - name: Publish package distribution to PyPi
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0

      # Send a slack notification to the auth alert channel
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 # v3.0.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "ELT-Dagster-Meltano Build ${{ steps.gitversion.outputs.assemblySemVer }} ${{ job.status }} <@${{ steps.user.outputs.member-id }}>"
            }
        if: ${{ always() }}